[package]
name = "woody"
version = "0.1.0"
edition = "2021"

[dependencies]
ecs_macros = { path = "macros/ecs" }
nalgebra-glm = "0.18.0"
winit = "0.28.6"
thiserror = "1.0.44"
vulkano = { git = "https://github.com/vulkano-rs/vulkano", branch = "master" }
vulkano-win = { git = "https://github.com/vulkano-rs/vulkano", branch = "master" }
vulkano-shaders = { git = "https://github.com/vulkano-rs/vulkano", branch = "master" }
bytemuck = "1.13.1"
lazy_static = "1.4.0"
ahash = "0.8.3"

[build-dependencies]
shaderc = "0.8.2"
